name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Notify Telegram
      uses: yanzay/notify-telegram@v0.1.0
      with:
        # Chat to send: chat id or @channel_name
        chat: ${{ secrets.TELEGRAM_TO }}
        # Telegram Bot token
        token: ${{ secrets.TELEGRAM_TOKEN }}
        # Job status
        status: New Push In the Port
